//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by CHESS.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDB_WPAWN                       101
#define IDB_WROOK                       102
#define IDB_WKNIGHT                     103
#define IDB_WBISHOP                     104
#define IDC_EDIT_GAMESTATS              104
#define IDB_WQUEEN                      105
#define IDB_WKING                       106
#define IDC_BLACK_SCORE                 106
#define IDB_BBISHOP                     107
#define IDB_BKING                       108
#define IDB_BKNIGHT                     109
#define IDB_BPAWN                       110
#define IDB_BQUEEN                      111
#define IDB_BROOK                       112
#define IDB_MPAWN                       113
#define IDB_MBISHOP                     114
#define IDB_MKING                       115
#define IDB_MKNIGHT                     116
#define IDB_MQUEEN                      117
#define IDB_MROOK                       118
#define IDD_DIALOG1                     122
#define IDD_POSITION_STATS              122
#define ID_LEFT                         32768
#define ID_DOWN                         32769
#define ID_RIGHT                        32770
#define ID_UP                           32771
#define ID_VIEW_REFRESH                 32772
#define ID_MOVE_SELECTPIECE             32774
#define ID_SPACEBAR                     32776
#define ID_HACK_SHOWALLMOVES            32777
#define ID_HACK_THREATENED              32779
#define ID_VIEW_GAMESTATISTICS          32780
#define ID_GAME_RESTORESAVED            32781
#define ID_LEVEL_DEPTH1                 32782
#define ID_LEVEL_DEPTH2                 32783
#define ID_LEVEL_DEPTH3                 32784
#define ID_LEVEL_DEPTH4                 32785
#define ID_LEVEL_DEPTH5                 32786
#define ID_LEVEL_DEPTH6                 32787
#define ID_ALGORITHM_MINIMAX            32788
#define ID_ALGORITHM_MINIMAXWITHALPHABETA 32789
#define ID_LEVEL_FORCEMOVE              32790
#define ID_MOVE_UNDO                    32791
#define ID_YOUR_MOVE                    57346
#define ID_THINKING                     57347
#define ID_CHECK                        57348
#define ID_CHECK_YOU                    57348
#define ID_MATE                         57349
#define ID_BLACKMATE                    57349
#define ID_CHECK_ME                     57350
#define ID_CHECK_STATUS                 57351
#define ID_WHITEMATE                    57352
#define ID_STARTPOS                     59142
#define ID_ENDPOS                       59143
#define ID_MESSAGE_BAR                  59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         109
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
